/**
 * Copied from Senec.IES Web application via dev-tools
 */
export const StatusStrings: Record<string, string> = {
    "1": "XCOM-FEHLER",
    "2": "LEISTUNGSMESSGERAET FEHLT",
    "3": "RUNDSTEUEREMPFAENGER AUS",
    "4": "ERSTLADUNG",
    "5": "WARTUNGSLADUNG",
    "6": "BEREIT FUER WARTUNG",
    "7": "BITTE WASSER NACHFUELLEN",
    "8": "VOLL-LADUNG MANUELL",
    "9": "ENTLADEN FREIGEBEN",
    "10":"VOLL-LADUNG",
    "11":"CELL BALNCING",
    "12":"SULFATLADUNG",
    "13":"AKKU-VOLL",
    "14":"SMART CHARGING",
    "15":"AKKU-LEER",
    "16":"ENTLADEN",
    "17":"ENTLADEN",
    "18":"ENTLADEN",
    "19":"PASSIV",
    "20":"PASSIV",
    "21":"PASSIV",
    "22":"CELL BALANCING MANUELL",
    "23":"SULFATLADUNG MANUELL",
    "24":"SICHERHEITSLADUNG",
    "25":"AKKU-SCHUTZ-MODUS",
    "26":"ENTLADEN",
    "27":"EG LADEN",
    "28":"EG PASSIV",
    "29":"EG FEHLER",
    "30":"EG ENTLADEN",
    "31":"NOTLADUNG",
    "32":"KAPAZITÄTSTEST"
};